name: git-auto-commit

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Update main.py code line
        run: |
          timestamp="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          if grep -q "^LAST_UPDATE =" main.py; then
            sed -i "s|^LAST_UPDATE = .*|LAST_UPDATE = \"$timestamp\"|" main.py
          else
            echo "LAST_UPDATE = \"$timestamp\"" >> main.py
          fi

      - name: Create empty commit
        run: |
          git config user.name "paleoignition77005"
          git config user.email "paleoignition@gmail.com"
          git add main.py
          git commit -m "Daily commit - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
